### ISSUE TITLE
IE11 and Edge support

### ISSUE THREAD

**Issue by taunoha** [terrymun/paver#19]
Hello,

I wonder what could be the reason that Paver doesn't work in Internet Explorer 11 and Microsoft Edge?

**Comment by terrymun** [comment]
Personally I have yet to test for IE support. Can you check your browser console and tell me what it says?

**Comment by taunoha** [comment]
Thanks for the quick reply! No errors in console :(
You can see my solution here: http://merko.ee/paepargi/en/location/ (the big panoram image)
Maybe I'm missing something? :s

**Comment by michaelkaaring** [comment]
Hi @terrymun! 
Are you any closer in resolving this issue? To me it looks like paver is not rendering at all. No paver events are fired and the parent don't have any paver css classes.

**Comment by michaelkaaring** [comment]
Nor are there any error messages in the console

**Comment by terrymun** [comment]
@taunoha @michaelkaaring It seems like the issue comes from IE/Edge declaring that it supports `DeviceOrientationEvent` yet not feeding any gyroscopic data. This is not caught in initial testing, which only checks for aberrant behavior in Firefox: https://github.com/terrymun/paver/blob/v1.3.3/src/js/jquery.paver.js#L820

Removing this check will fix the issue.
